### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL during node install

### ISSUE THREAD

**Issue by tylershumaker** [adaptlearning/adapt_authoring#1042]
during node install on Windows 7 OS
 node install
C:\Users\...\Documents\GitHub\aat\adapt_authoring\lib\usermanager.js:139
              var tenantName = `${profile.auth}-${newUser._id}`;
                               ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\...\Documents\GitHub\aat\adapt_authoring\lib\permissions.js
:5:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

C:\Users\...\Documents\GitHub\aat\adapt_authoring\lib\usermanager.js:414
        logger.log('error', `Unable to retrieve tenant ${data._tenantId} for u
                            ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\...\Documents\GitHub\aat\adapt_authoring\lib\permissions.js
:5:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by brian-learningpool** [comment]
You most likely have an older, unsupported version of Node.js.  Please install a version great than 4.2 as outlined here:
https://github.com/adaptlearning/adapt_authoring/wiki/Install-on-Server#install-nodejs

**Comment by tylershumaker** [comment]
That was the issue.  Updated to Node.js solved the issue.
