### ISSUE TITLE
Issue Asset Management

### ISSUE THREAD

**Issue by zilliotech** [adaptlearning/adapt_authoring#1263]
Hi,

I m a new bee in authoring tool. After installing all the software mentioned finally i have got my Adapt running. The only thing which i m facing is i couldn't b able to upload any assets and don't know what is the issue. Can anybody help me out.

Console Error : 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Uncaught TypeError: Cannot read property 'message' of undefined origin.js?20160714094911006:179

Server Response Error: spawn ffprobe ENOENT
   at exports._errnoException (util.js:873:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
   at onErrorNT (internal/child_process.js:344:16)
   at nextTickCallbackWith2Args (node.js:442:9)
   at process._tickDomainCallback (node.js:397:17)

**Comment by taylortom** [comment]
Closing due to inactivity
