### ISSUE TITLE
'deprecated' warnings & fail during install (OSX)

### ISSUE THREAD

**Issue by dzg** [adaptlearning/adapt_authoring#1737]
Hi, I'm brand new to Adapt and installing for the first time (on OSX).

I'm getting a lot of warnings. During `npm install -g adapt-cli` I get:
```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

And during `npm install --production` I get:

```
npm WARN deprecated bower@1.6.5: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3 and read the breaking changes at https://github.com/niftylettuce/email-templates#v3-breaking-changes 📫
npm WARN deprecated nodemailer@2.5.0: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
npm WARN deprecated mongodb@2.0.48: Please upgrade to 2.2.19 or higher
npm WARN deprecated URIjs@1.12.1: package renamed to "urijs" (lower-case), please update accordingly
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated mongodb@2.1.21: Please upgrade to 2.2.19 or higher
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

```

Then during `node install` (with or without `sudo`):
```
 npm 
 WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

 npm WARN
  deprecated connect@2.19.6: connect 2.x series is deprecated

 npm WARN 
 deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

 npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

 npm WARN 
 deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

 npm 
 notice created a lockfile as package-lock.json. You should commit this file.
```

And then after `> Sender email address` it fails with:
```
Checking configuration, please wait a moment ... 
readline.js:1017
            throw err;
            ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/Users/zeev/adapt_authoring/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zeev/adapt_authoring/node_modules/bower/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

Thanks!

**Comment by moloko** [comment]
@dzg as discussed, please could you try again using the LTS version of Node? Also it might be worth waiting 24 hours to give us a chance to sort out the problems we are having with our Bower repository.

**Comment by dzg** [comment]
Yes, it worked with node 6; I had v8 installed.

**Comment by taylortom** [comment]
In the interests of stability, we stick to LTS releases. We're looking to push out a release to support v8 in the coming months.
