### ISSUE TITLE
node server & upgrade broken with Node v8

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#1769]
## Error Log
<details>
<summary><code>node upgrade</code></summary>

```console
module.js:515
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (D:\adapt_authoring\node_modules\bower\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\adapt_authoring\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
```
</details>

## Steps to Reproduce
1. Install Node v8
1. Run `node server`/`node upgrade`/`node install`

## Versions
  - Authoring Tool Version: 0.4.0
  - Operating System: Windows 10
  - Node Version: 8.8.1

## Additional Information
I would've liked to do a blanket upgrade of all dependencies but I then got an error with `async` later on in the upgrade script.

Node v8 is due to enter [LTS](https://github.com/nodejs/Release#lts-schedule1) on 31/10/17.

**Comment by benhalverson** [comment]
I was able to get around this bug by adding this flag --expose-internals. In my case I was doing node install `node --expose-internals install`
