### ISSUE TITLE
Install/upgrade script doesn't support private bower packages

### ISSUE THREAD

**Issue by benhalverson** [adaptlearning/adapt_authoring#1801]
## Expected Behaviour
No errors during install
## Actual Behaviour
blows up because it can't find a package that is not published on bower
## Steps to Reproduce
I'm using defaults for adapt auth with the exception of my own bitbucket link 
I also have a custom theme under themes.

```
Tip: just press ENTER to accept the default value in brackets.
> Server port (5000)
> Server name (localhost)
> Database host (localhost)
> Master database name (adapt-tenant-master)
> Database server port (27017)
> Data directory path (data)
> Session secret (value used when saving session cookie data) (your-session-secret)
> Git repository URL to be used for the authoring tool source code (https://github.com/adaptlearning/adapt_authoring.git)
> Git repository URL to be used for the framework source code (https://github.com/adaptlearning/adapt_framework.git) git@bitbucket.org:viscira/private.git
> Specific git revision to be used for the framework. Accepts any valid revision type (e.g. branch/tag/commit) (tags/v2.2.3) v0.0.5
> Are you using ffmpeg? y/N (N)
> Will you be using an SMTP server? (used for sending emails) y/N (N)
Now we need to configure the master tenant.
Tip: just press ENTER to accept the default value in brackets.

> Set a unique name for your tenant (master)
> Set the display name for your tenant (Master)

Tenant 'master' already exists. It must be deleted for install to continue.
> Continue? (Y/n) (Y)

Cloned git@bitbucket.org:viscira/private....git successfully.
/temp/5a1f4c1e87df92c424c94d6a/adapt_framework switched to revision v0.0.5
Node dependencies installed successfully.
/ Updating Adapt framework plugin 'adapt-custom-theme'
/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:155
                throw e;
                ^

ReferenceError: packageName is not defined
    at Logger.<anonymous> (/Users/bhalverson/projects/adapt-node8.5/lib/bowermanager.js:162:40)
    at emitOne (events.js:115:13)
    at Logger.emit (events.js:210:7)
    at Logger.emit (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/bhalverson/projects/adapt-node8.5/node_modules/bower/lib/commands/index.js:45:25
    at _fulfilled (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/bhalverson/projects/adapt-node8.5/node_modules/bower/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## Versions
  - Authoring Tool Version: v0.4.0
  - Framework Version: 2.1.2
  - Operating System: OSX 10.12.6

**Comment by taylortom** [comment]
Hi @benhalverson,

Am I correct in my understanding that this is an issue related to your using custom (non-bower-registered) components in your framework's adapt.json?

**Comment by canstudios-louisem** [comment]
Yes looks like your trying to install a custom framework version with a custom plugin that is not in bower this isnt an issue with the AT.

**Comment by benhalverson** [comment]
Hi @taylortom @canstudios-louisem  yes I have two custom plugins. One is my own theme which is a copy of the vanilla core theme. The other is a copy of the adapt-text component with different styling and mark up.
I'm not able to publish my plugins publicly so what's the alternative to using bower?

**Comment by taylortom** [comment]
Closing due to inactivity & impending deprecation of the legacy codebase.
