### ISSUE TITLE
Stuck on final step of install

### ISSUE THREAD

**Issue by rocky3d** [adaptlearning/adapt_authoring#1865]
## Expected Behaviour

Clean install

## Actual Behaviour

I got stuck at when installing the AdaptLearning at the last step, I got so many things installed as requested but stuck on the final step...

module.js:540
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\Users\Administrator\adapt_authoring\node_modules\b
ower\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\adapt_authoring\node_modules\b
ower\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

C:\Users\Administrator\adapt_authoring>node install

Found an existing config.json file. Do you want to use the values in this file d
uring install?
> Use existing config values? y/N (N) y

This script will install the application. Please wait ...

Now setting configuration items.
Now configuring the master tenant.

module.js:540
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\Users\Administrator\adapt_authoring\node_modules\b
ower\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\adapt_authoring\node_modules\b
ower\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

C:\Users\Administrator\adapt_authoring>

**Comment by taylortom** [comment]
@rocky3d can you please post this request on the [community forums](https://community.adaptlearning.org/mod/forum/view.php?id=4), as we try to keep this issues repo for specific technical bugs etc.

As a starting point, I'd check that you're using a compatible version of node (v4 or v6), and that there's not an issue with the install node modules (maybe try reinstalling the dependencies by completely deleting the `node_modules` folder and re-running `npm install`).
