### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by dymitar** [adaptlearning/adapt_authoring#2092]
## Expected Behaviour
After login to have full application accessible
## Actual Behaviour
After login the application is partially loaded without any possible actions.
There is an exception (see below):

[root@web4 adapt_authoring]# node server
info: [02 Oct 2018 21:19:13 +02:00] configuration loaded from /var/www/adapt_authoring/conf/config.json
info: [02 Oct 2018 21:19:13 +02:00] Supporting the following authentication types:
info: [02 Oct 2018 21:19:13 +02:00] - local
info: [02 Oct 2018 21:19:13 +02:00] Adapt authoring tool 0.6.0.
info: [02 Oct 2018 21:19:13 +02:00] Adapt framework 2.2.5.
(node:10746) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
info: [02 Oct 2018 21:19:14 +02:00] Connection established: adapt-tenant-master
(node:10746) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:10746) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
Error: Failed to determine user's tenant!
    at Object.getDatabase (/var/www/adapt_authoring/lib/database.js:427:19)
    at /var/www/adapt_authoring/plugins/content/tag/index.js:76:16
    at /var/www/adapt_authoring/lib/rest.js:115:7
    at Layer.handle [as handle_request] (/var/www/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/adapt_authoring/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/adapt_authoring/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/adapt_authoring/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/var/www/adapt_authoring/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:317:13)
    at /var/www/adapt_authoring/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at /var/www/adapt_authoring/lib/permissions.js:604:9
    at Layer.handle [as handle_request] (/var/www/adapt_authoring/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:317:13)
    at /var/www/adapt_authoring/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/adapt_authoring/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/var/www/adapt_authoring/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/var/www/adapt_authoring/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/var/www/adapt_authoring/node_modules/send/index.js:421:12)
    at next (/var/www/adapt_authoring/node_modules/send/index.js:736:16)
    at onstat (/var/www/adapt_authoring/node_modules/send/index.js:725:14)

## Steps to Reproduce
1. Start the application
2. Login
3. You will have the exception and practically empty dashboard
4. If the login is normal (in some cases after clean installation), stop the application and start it again
5. Login
6. You will have the exception and practically empty dashboard
7. This might need 2-3 stops of the application.
8. Once it happens, there is no cure. Tried to clean cookies in the browser, data from sessions table...

## Versions
  - Authoring Tool Version: o.6 (tested with 0.5 - the same behavior)
  - Framework Version: 2.2.5
  - Node.js Version: 8.12.0 (tested with 8.11.3 as well)
  - MongoDB Version: 3.6 (tested with 3.4, 3.6 and 4.0)
  - Operating System: Centos 6.10 (tested with Ubuntu 16.04 as well)
  - Browser: Chrome (tested with Opera and Firefox as well)

All the installations are clean install, accepting default values during the installation.
After every change of node version and mongodb version clean install was performed.
To me it seems it has issues with database connection or database object

**Comment by dymitar** [comment]
The problem is found and it is quite unexpected. The problem is related to the antivirus tool on the client PC. It intercepts HTTP Traffic and introduces this problem. Probably related do some session cookies damage or POST actions...
The antivirus tool in this case is bitdefender and the connection is not secure (HTTP). After adding the URL to the exceptions everything is working without problems.
