### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by nakaravi** [adaptlearning/adapt_authoring#2162]
throw new TypeError('path to favicon.ico is required')

TypeError: path to favicon.ico is required
    at favicon (D:\Projects\adapt_authoring\node_modules\serve-favicon\index.js:55:11)
    at Origin.createServer (D:\Projects\adapt_authoring\lib\application.js:255:16)
    at D:\Projects\adapt_authoring\lib\application.js:376:9
    at D:\Projects\adapt_authoring\lib\application.js:364:7
    at D:\Projects\adapt_authoring\lib\application.js:545:16
    at D:\Projects\adapt_authoring\lib\installHelpers.js:170:14
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3888:9
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\Projects\adapt_authoring\node_modules\async\dist\async.js:1062:13)
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:969:16
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3885:13
    at D:\Projects\adapt_authoring\lib\installHelpers.js:145:5
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3888:9
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\Projects\adapt_authoring\node_modules\async\dist\async.js:1062:13)
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:969:16
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3885:13
    at getInstalledFrameworkVersion (D:\Projects\adapt_authoring\lib\installHelpers.js:132:12)
    at D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3880:24
    at eachOfArrayLike (D:\Projects\adapt_authoring\node_modules\async\dist\async.js:1069:9)
    at eachOf (D:\Projects\adapt_authoring\node_modules\async\dist\async.js:1117:5)
    at _parallel (D:\Projects\adapt_authoring\node_modules\async\dist\async.js:3879:5)

**Comment by taylortom** [comment]
@nakaravi we need some more specific details on what's gone wrong (see the [bug template](https://github.com/adaptlearning/adapt_authoring/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) for more info).

The above error by itself shouldn't cause any issues with the running of the app, as it's only related to the [favicon file](https://en.wikipedia.org/wiki/Favicon). Sometimes this error's thrown when an installation has failed (due to an invalid or missing `conf/config.json` file). If this is the case, I'd suggest running through the install process again.
