### ISSUE TITLE
_trickle config attribute error after upgrade

### ISSUE THREAD

**Issue by mattwkcc** [adaptlearning/adapt_authoring#2205]
## Expected Behaviour
Ability to login to adapt after upgrade

## Actual Behaviour
Login page displays: "An error occurred while getting schemas." 

File /var/log/adapt.log displays:
`Error: Already found extension config attribute with key _trickle (adapt-contrib-trickle)
Error: Already found extension config attribute with key _trickle (adapt-contrib-trickle)
    at /opt/adaptlearning/adapt_authoring/lib/contentmanager.js:694:31
    at /opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:1069:9)
    at eachOf (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:3172:5)
    at processPluginLocations (/opt/adaptlearning/adapt_authoring/lib/contentmanager.js:681:13)
    at processPlugin (/opt/adaptlearning/adapt_authoring/lib/contentmanager.js:644:7)
    at /opt/adaptlearning/adapt_authoring/lib/contentmanager.js:628:15
    at /opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:3110:16
    at replenish (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:1011:17)
    at /opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/opt/adaptlearning/adapt_authoring/node_modules/async/dist/async.js:1046:16)
    at /opt/adaptlearning/adapt_authoring/lib/contentmanager.js:627:19
    at /opt/adaptlearning/adapt_authoring/node_modules/mongoose/lib/model.js:4484:16
    at (anonymous function).call (/opt/adaptlearning/adapt_authoring/node_modules/mongoose/lib/query.js:3560:7)
    at process.nextTick (/opt/adaptlearning/adapt_authoring/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

## Steps to Reproduce
1. node upgrade
2. restart adapt service
3. Try logging in

## Versions
  - Authoring Tool Version: 0.6.2
  - Framework Version: 2.3.2
  - Node.js Version: 8.11.3
  - MongoDB Version: 3.6.6
  - Operating System: Ubuntu 16.04.5 LTS
  - Browser: Chrome, Safari

**Comment by taylortom** [comment]
I've just tested an upgrade from 0.6.0 to 0.6.2, with no issues. Do you have any custom extensions installed (or perhaps forks of trickle) that use the attribute `_trickle`?

**Comment by tomgreenfield** [comment]
Closing due to lack of response.
