### ISSUE TITLE
Error: Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2478]
## Expected Behaviour

All node modules install correctly.

## Actual Behaviour

Noticed this error during/after one of our upgrades:
```console
{ Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Module.Hook._require.Module.require (/root/.nvm/versions/node/v10.9.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:27)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/data/adapt/testing.kineoadapt.com/node_modules/connect-mongodb-session/index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module.Hook._require.Module.require (/root/.nvm/versions/node/v10.9.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:37)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/data/adapt/testing.kineoadapt.com/lib/application.js:39:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module.Hook._require.Module.require (/root/.nvm/versions/node/v10.9.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:37)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/data/adapt/testing.kineoadapt.com/server.js:1:75) code: 'MODULE_NOT_FOUND' }
```

Quick fix was to navigate to _node_modules/connect-mongodb-session_ and manually run `npm install`.

## Steps to Reproduce
Occurred on only one of our instances following a `node upgrade` from 0.10.0 to 0.10.2.

## Versions
  - Authoring Tool Version: 0.10.2
  - Framework Version: 4.4.1
  - Node.js Version: 10.9
  - MongoDB Version: 3.2.22
  - Operating System: Ubuntu 16.04.5 LTS

**Comment by fkcailiniyazi** [comment]
Hi Tom,

check this comment from community:
[](https://community.adaptlearning.org/mod/forum/discuss.php?d=3721#p13525)
