### ISSUE TITLE
Cannot import framework source with nested asset folders

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#2486]
## Expected Behaviour

Unsure what the priority is for being able to import nested asset folders since exports don't contain these.

But at the very least we should handle the error and allow it to feed through to the frontend. The uncaught exception is triggered by running the following on a directory:
https://github.com/adaptlearning/adapt_authoring/blob/859227bcbde3090b04735ccbda00c096d88996f0/plugins/output/adapt/helpers.js#L138
Can be caught with:
```js
rs.on('error', () => {});
```

## Actual Behaviour

No import, and unhandled 500 response:
```console
application.js:630 Error: EISDIR: illegal operation on a directory, read
application.js:630 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (D:\adapt_authoring\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (D:\adapt_authoring\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (D:\adapt_authoring\node_modules\express\lib\response.js:267:15)
    at ServerResponse.send (D:\adapt_authoring\node_modules\express\lib\response.js:158:21)
    at D:\adapt_authoring\routes\import\index.js:48:55
    at D:\adapt_authoring\plugins\output\adapt\importsource.js:74:54
    at wrapper (D:\adapt_authoring\node_modules\async\dist\async.js:272:20)
    at iteratorCallback (D:\adapt_authoring\node_modules\async\dist\async.js:499:17)
    at D:\adapt_authoring\node_modules\async\dist\async.js:325:20
    at CB (D:\adapt_authoring\node_modules\fs-extra\lib\remove\rimraf.js:57:5)
    at FSReqCallback.oncomplete (fs.js:157:23)
```

## Steps to Reproduce
1. Import a source with a nested assets folder e.g. `src/course/en/images/nested`

## Versions
  - Authoring Tool Version: 0.10.2
  - Framework Version: 5.1.0
  - Node.js Version: 12.11.1

**Comment by tomgreenfield** [comment]
Closing since we now handle the error; can be reopened in the future if we want to handle nested folders.
