### ISSUE TITLE
New installs return an error when running migrations

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#2681]
## Expected Behaviour
A clean install should work 

## Actual Behaviour
Returns the following error:

ERROR:  Error: Couldn't parse ARIA level defaults
    at up (\local\deleteme\migrations\20220908105711-convertarialabels.js:22:13)
    at migrateItem (\local\deleteme\node_modules\migrate-mongo\lib\actions\up.js:25:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async pEachSeries (\local\deleteme\node_modules\p-each-series\index.js:8:23)
    at async module.exports (\local\deleteme\node_modules\migrate-mongo\lib\actions\up.js:51:3)
    at async runMigrations (\local\deleteme\lib\installHelpers.js:320:12) {
  migrated: []
}

Install was unsuccessful. Please check the console output.

On clean install throws an error [here](https://github.com/adaptlearning/adapt_authoring/blob/master/migrations/20220908105711-convertarialabels.js#L21). @taylortom should we check for config collection existing & if not return and log an error.

## Steps to Reproduce
1. Run a clean install of v0.11.0

## Versions
  - Authoring Tool Version: v0.11.0
  - Framework Version: latest
  - Node.js Version: 14
  - MongoDB Version: 4
  - Operating System: Windows 10

**Comment by mrblonde77** [comment]
I also have the problem with a clean install of adapt authoring with version v0.11.0.

Versions
Authoring Tool Version: v0.11.0
Framework Version: latest
Node.js Version: 16
MongoDB Version: 4
Operating System: Windows 10

**Comment by SmallDigital** [comment]
I have a similar issue installing AAT from scratch on a Mac, OS Ventura 13.0
Console:
Web application built successfully.
ERROR:  Error: Couldn't parse ARIA level defaults
    at up (/Users/lauraleonard/AAT/adapt_authoring/migrations/20220908105711-convertarialabels.js:22:13)
    at migrateItem (/Users/lauraleonard/AAT/adapt_authoring/node_modules/migrate-mongo/lib/actions/up.js:25:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async pEachSeries (/Users/lauraleonard/AAT/adapt_authoring/node_modules/p-each-series/index.js:8:23)
    at async module.exports (/Users/lauraleonard/AAT/adapt_authoring/node_modules/migrate-mongo/lib/actions/up.js:51:3)
    at async runMigrations (/Users/lauraleonard/AAT/adapt_authoring/lib/installHelpers.js:320:12) {
  migrated: []
}

**Comment by jroed** [comment]
I can reproduce this with a clean install.

Versions
Authoring Tool Version: v0.11.0
Framework Version: latest
Node.js Version: 14.21.1
MongoDB Version: 6.0.2
Operating System: Windows 10

I also got the following additional error message: "Could not migrate up 20220908105711-convertarialabels.js: Couldn't parse ARIA level defaults"
