### ISSUE TITLE
Upgrade errror Unexpected token '.'

### ISSUE THREAD

**Issue by danbuntu** [adaptlearning/adapt_authoring#2695]
## Expected Behaviour

Running npm upgrade upgrades adapt without errors

## Actual Behaviour
I ran npm upgrade and got 'Upgrade was unsuccessful. Please check the console output.' but no console output

I then ran it again and got 'upgrade not needed'
I checked conf/config.json' and the framework version hadn't been changed.

I then ran the upgrade again and choose the manual install. I specified the latest framework version v5.25.2 and I get the following error

ERROR: /var/www/html/adapt_authoring/migrations/20220908105711-convertarialabels.js:20
    const props = origin().db.getModel('config')?.schema?.tree?._accessibility?._ariaLevels?.properties;
                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.require (/var/www/html/adapt_authoring/node_modules/migrate-mongo/lib/utils/module-loader.js:3:12)
    at Object.loadMigration (/var/www/html/adapt_authoring/node_modules/migrate-mongo/lib/env/migrationsDir.js:101:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async migrateItem (/var/www/html/adapt_authoring/node_modules/migrate-mongo/lib/actions/up.js:18:25)
    at async pEachSeries (/var/www/html/adapt_authoring/node_modules/p-each-series/index.js:8:23)
    at async module.exports (/var/www/html/adapt_authoring/node_modules/migrate-mongo/lib/actions/up.js:51:3)
    at async Object.runMigrations (/var/www/html/adapt_authoring/lib/installHelpers.js:320:12) {
  migrated: []
}

Upgrade was unsuccessful. Please check the console output.

## Versions
  - Authoring Tool Version: 0.10.5 to latest
  - Framework Version: 5.1.0 to latest
  - Node.js Version: v12.22.12
  - MongoDB Version: v4.2.23
  - Operating System: ubuntu
  - Browser: chrome

**Comment by danbuntu** [comment]
I just had a similar error when trying to a do a completely fresh install

Set a unique name for your tenant (master) error [21 Feb 23 16:22:53 +00:00] Could not migrate up 20220908105711-convertarialabels.js: Unexpected token '.'

This is on a brand new server running ubuntu 22.04
node: v12.22.9

**Comment by Lamboy88** [comment]
same for me with a fresh install. would be great to have a solution for this, or to know how to resolve.

**Comment by simondate** [comment]
@Lamboy88 , use Node v14 to fix this.

I would recommend using [NVM](https://github.com/nvm-sh/nvm) to easily swap between different versions of Node.

**Comment by Lamboy88** [comment]
Thanks a lot for the hint, it worked great!!
