### ISSUE TITLE
Updating to v0.11.2

### ISSUE THREAD

**Issue by fosterc1** [adaptlearning/adapt_authoring#2737]
## Expected Behaviour
No errors on install

## Actual Behaviour
After running node upgrade from v0.11.1 I'm getting the following error, this doesn't appear to be affecting the build or using AAT, but thought I'd raise it.

node:internal/modules/cjs/loader:353
      const err = new Error(
                  ^

Error: Cannot find module '/home/nhsc-live/node_modules/mongodb/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nhsc-live/node_modules/migrate-mongo/lib/env/database.js:1:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nhsc-live/node_modules/migrate-mongo/lib/migrate-mongo.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.runMigrations (/home/nhsc-live/lib/installHelpers.js:315:26)
    at runMigrations (/home/nhsc-live/upgrade.js:170:22)
    at /home/nhsc-live/node_modules/async/dist/async.js:3674:28
    at replenish (/home/nhsc-live/node_modules/async/dist/async.js:446:21)
    at iterateeCallback (/home/nhsc-live/node_modules/async/dist/async.js:430:21)
    at /home/nhsc-live/node_modules/async/dist/async.js:327:20
    at /home/nhsc-live/node_modules/async/dist/async.js:3679:17
    at /home/nhsc-live/upgrade.js:166:9 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/nhsc-live/node_modules/mongodb/package.json',
  requestPath: 'mongodb'
}

## Steps to Reproduce
1.
1.
1.

## Versions
  - Authoring Tool Version: v0.11.1 to v0.11.2
  - Framework Version: v5.31.27 to v5.32.2
  - Node.js Version:
  - MongoDB Version:
  - Operating System:
  - Browser:

**Comment by simondate** [comment]
@fosterc1 with the 0.11.2 we upgraded the Node version. You should have upgraded from 12/14 to [16/18](https://github.com/adaptlearning/adapt_authoring/blob/master/package.json#L16). You should upgrade your Node version before upgrading
