### ISSUE TITLE
No options on Adapt Dashboard

### ISSUE THREAD

**Issue by thalesuts** [adaptlearning/adapt_authoring#2771]
I can login to the master tenant. I have 4 options

![AdaptOptions](https://github.com/adaptlearning/adapt_authoring/assets/173313261/3f8a7367-8204-44aa-8481-85be8f5f15f7)

Dashboard and Asset Management do nothing
Plugins and Users work

There is no create button or anything so unable to create anything.. please help

## Versions
  - Authoring Tool Version: 0.11.3
  - Framework Version: 5.39.15
  - Node.js Version:  v16.20.2 x64
  - MongoDB Version: 7.0.11 x64
  - Operating System: Windows 11 x64
  - Browser: Edge
  - Git Version: 2.45.2 x64

**Comment by simondate** [comment]
Can you open your web browser's developer tools? It may have a more helpful error message there

**Comment by giandre** [comment]
I have the same problem. The logs show this is an tenant issue.

info [30 Jul 24 16:45:34 -04:00] configuration loaded from D:\adapt_authoring\conf\config.json
info [30 Jul 24 16:45:34 -04:00] Supporting the following authentication types:
info [30 Jul 24 16:45:34 -04:00] - local
info [30 Jul 24 16:45:34 -04:00] Connection established: adapt-tenant-master
info [30 Jul 24 16:45:35 -04:00] Adapt authoring tool 0.11.3.
info [30 Jul 24 16:45:35 -04:00] Adapt framework 5.40.5.
info [30 Jul 24 16:45:35 -04:00] Server started listening on port 5000
Error: Failed to determine user's tenant!
    at Object.getDatabase (D:\adapt_authoring\lib\database.js:416:19)
    at D:\adapt_authoring\plugins\content\tag\index.js:76:16
    at D:\adapt_authoring\lib\rest.js:115:7
    at Layer.handle [as handle_request] (D:\adapt_authoring\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\adapt_authoring\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\adapt_authoring\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\adapt_authoring\node_modules\express\lib\router\layer.js:95:5)
    at D:\adapt_authoring\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\adapt_authoring\node_modules\express\lib\router\index.js:346:12)
    at next (D:\adapt_authoring\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle [as handle_request] (D:\adapt_authoring\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (D:\adapt_authoring\node_modules\express\lib\router\index.js:328:13)
    at D:\adapt_authoring\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\adapt_authoring\node_modules\express\lib\router\index.js:346:12)
    at next (D:\adapt_authoring\node_modules\express\lib\router\index.js:280:10)
    at D:\adapt_authoring\lib\application.js:308:7
    at Layer.handle [as handle_request] (D:\adapt_authoring\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\adapt_authoring\node_modules\express\lib\router\index.js:328:13)
    at D:\adapt_authoring\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\adapt_authoring\node_modules\express\lib\router\index.js:346:12)
    at next (D:\adapt_authoring\node_modules\express\lib\router\index.js:280:10)
    at D:\adapt_authoring\lib\permissions.js:495:16
    at Layer.handle [as handle_request] (D:\adapt_authoring\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\adapt_authoring\node_modules\express\lib\router\index.js:328:13)
    at D:\adapt_authoring\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\adapt_authoring\node_modules\express\lib\router\index.js:346:12)
    at next (D:\adapt_authoring\node_modules\express\lib\router\index.js:280:10)
    at SendStream.error (D:\adapt_authoring\node_modules\serve-static\index.js:121:7)
    
    
I checked mongodb and I can see that the database was created and I see a tenant, user, and all other components. This is what the tenant document says:
_id
66a9505620d147392c898b65
_isDeleted
false
isMaster
true
name
"adaptmaster"
displayName
"adaptmaster"

database
Object
createdAt
2024-07-30T20:43:02.351+00:00
updatedAt
2024-07-30T20:43:02.351+00:00
__v
0

I am not a developer so I have no idea what to do and ChatGPT basically asked me to update a bunch of files :)... so I stopped.

**Comment by marticus123** [comment]
I am having the same issue
