### ISSUE TITLE
Help - Stuck Installing v0.9.0 Again

### ISSUE THREAD

**Issue by DeepSeaCatz** [adaptlearning/adapt_authoring#2795]
I've been trying to get my team up to date with the latest of Adapt. We've been using Adapt for 6 years and our last update was to v0.9.0, using v2.4.0 framework.

We currently want to upgrade out adapt version to the latest, but during the process of doing so, I've messed up my nodes version, MongoDB version and potentially npm.

It's been **2 weeks** that I keep trying to install version 0.9.0 properly, while trying to understand the correct versions required so I know for sure what to install on the other computers of my colleagues. I'm starting to get desperate. There are so many strict dependencies that I'm starting to go insane. Even ChatGPT and Claude.ai don't know and get me into a dependency loop.

This is my current way of installing so far :
1. Use node version 10.16.1 (nvm use 10.16.1)
2. Create new folder named adapt in C:\
3. Open command prompt and write the following commands:
- cd C:\adapt
- git clone https://github.com/adaptlearning/adapt_authoring.git
- git checkout tags/v0.9.0
- npm install -g grunt-cli
- npm install -g bower
- npm install
- node install
4. Spam Enter to have the default choices
5. Get stuck when linking it to the MongoDB:
![image](https://github.com/user-attachments/assets/9b895cda-27af-42ba-b11a-80d5ad740427)

Currently, I understand that MongoDB requires to be at **version 4**. I've tried to use version 4.4, but there were issues connecting to the database when adapt was installed. Since the current oldest version of [MSI possible to download](https://www.mongodb.com/try/download/community) is version 5.0.30, I had to go into the [archives](https://www.mongodb.com/download-center/community/releases/archive), which only have a Zip version:
Windows x64
Archive: [mongodb-win32-x86_64-2008plus-ssl-4.0.28.zip](https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.28.zip)

Claude.ai helped me set it up successfully, which I would have never been able to do without.

For the node versions, I've tried various versions, which all seem to have a different effect when doing npm install and node install:
![image](https://github.com/user-attachments/assets/75286c94-b14a-44fb-84d9-0e7f00090fe5)

I tried npm install with version 16, then going switching back to version 10 for node install, vice-verca, all of the version 1 install or mix. It seemed that installing with a version requires another dependency for it to work, so the current way the 0.9.0 is setup is not possible with all 1 version of 8-10 as recommended.

If I use node version **8.16.2** - **10.16.1** or **14.19.**0, I get this error:
```
C:\adapt\adapt_authoring>node install
C:\adapt\adapt_authoring\node_modules\winston-transport\node_modules\readable-stream\lib\ours\util.js:5
const AbortSignal = globalThis.AbortSignal || require('abort-controller').AbortSignal
                    ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (C:\adapt\adapt_authoring\node_modules\winston-transport\node_modules\readable-stream\lib\ours\util.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\adapt\adapt_authoring\node_modules\winston-transport\node_modules\readable-stream\lib\stream.js:31:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

```
If I use version node 12
```
(node:3888) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
error [28 Oct 24 15:52:17 -04:00] Failed to load content plugin of type: bower
```

If anyone out there could help me list the correct version to install **Authoring Tool v0.9.0** and **Framework v2.4.0**, I would appreciate you a lot! The main goal is to have both v0.9.0 and the most up to date version installed at the same time to easily access both version at once on different ports. This way it will be easier to transfer all the content over for upgrade.

Thanks

**Comment by taylortom** [comment]
Ok, so it looks like the current dependency versions at the time of release were:
- Node.js 10
- MongoDB 4.2
- Grunt 1.0.4
- A global bower install is not necessary as far as I'm aware

Can you check that you're able to access your MongoDB server (this should be possible by running the `mongo` command) - if this doesn't work, you'll need to figure out what's gone wrong with your MongoDB install before proceeding.

**Comment by DeepSeaCatz** [comment]
Sorry for the late reply. Thank you for the specific dependencies required! I have forgotten about Grunt version 1.0.4. I have been trying to resolve this on the side of my accumulated projects.

I've finally been successful in running `mongo` command. This wouldn't work even after adding the bin path to the environment variable, but this command resolved it: `setx /m PATH "C:\Program Files\MongoDB\Server\4.2\bin;%PATH%"` 

I also discovered that I had to delete all 3 grunt files under `AppData\Roaming\npm` to install a new grunt version. I was wondering why I couldn't go foreword.

Right now it seems I am stuck I am stuck from going forward because of MongoDB in the node modules.:

![image](https://github.com/user-attachments/assets/b9d4d730-0982-4b29-9bc5-53a3d630fd1e)

From what I see online is that I am not able to make connection with MongoDB and require some kind of authentification? I have MongoDB running as a services.

I tried creating a admin account and a user account in MongoDB Compass and using the command, but it seems to have created more issues. I am using the version 4.2.25 and npm is at version 6.14.16 (I'm not sure if should use an older or newer version).

I didn't expected to have had this amount of issues. I'm a front-end Web developer, so working the in the back-end is a very different way of problem solving. Thanks for the help!
